Watt-32 tcp/ip: /home/fosco/src/SSH2DOS/watt32/src/pctcp.c File Reference
pctcp.c File Reference
Data Structures
struct ip6_packet
struct tcp_pkt
struct tcp6_pkt
Functions
W32_CLANG_PACK_WARN_OFF ()
W32_CLANG_PACK_WARN_DEF ()
int W32_CALL udp_open (_udp_Socket *s, WORD lport, DWORD ip, WORD port, ProtoHandler handler)
UDP active open.
static void udp_close (const _udp_Socket *udp)
Since UDP is stateless, simply reclaim the local-port and unthread the socket from the list.
int W32_CALL udp_SetTTL (_udp_Socket *s, BYTE ttl)
Set the TTL on an outgoing UDP datagram.
int W32_CALL tcp_open (_tcp_Socket *s, WORD lport, DWORD ip, WORD rport, ProtoHandler handler)
Actively open a TCP connection.
int W32_CALL tcp_listen (_tcp_Socket *s, WORD lport, DWORD ip, WORD port, ProtoHandler handler, WORD timeout)
Passively opens TCP a connection.
void _tcp_close (_tcp_Socket *s)
Close a TCP connection.
_tcp_Socket * _tcp_abort (_tcp_Socket *s, const char *file, unsigned line)
Abort a TCP connection.
int _tcp_sendsoon (_tcp_Socket *s, const char *file, unsigned line)
Schedule a transmission pretty soon.
_tcp_Socket * _tcp_unthread (_tcp_Socket *ds, BOOL free_tx)
Unthread a socket from the tcp socket list, if it's there.
int W32_CALL tcp_established (const _tcp_Socket *s)
Returns 1 if TCP connection is established.
_tcp_Socket * _tcp_handler (const in_Header *ip, BOOL broadcast)
The main TCP input handler.
static BOOL udp_checksum (const in_Header *ip, const udp_Header *udp, int len)
Verify checksum for an UDP packet.
static _udp_Socket * udp_demux (const in_Header *ip, BOOL ip_bcast, DWORD destin, WORD srcPort, WORD dstPort, BOOL *udp_err)
Demultiplexer for incoming UDP packets.
_udp_Socket * _udp_handler (const in_Header *ip, BOOL broadcast)
Handler for incoming UDP packets.
void tcp_Retransmitter (BOOL force)
Called periodically to perform retransmissions.
WORD W32_CALL tcp_tick (sock_type *s)
Must be called periodically by user application (or BSD socket API).
static int udp_write (_udp_Socket *s, const BYTE *data, int len)
Write an UDP packet.
static int udp_read (_udp_Socket *s, BYTE *buf, int maxlen)
Read from UDP socket.
static void sock_reduce_mss (sock_type *s, WORD MTU)
Reduce socket MSS upon receiving ICMP_UNREACH_NEEDFRAG.
void _udp_cancel (const in_Header *ip, int icmp_type, int icmp_code, const char *msg, const void *arg)
Cancel an UDP socket.
static BOOL tcp_stress_test (_tcp_Socket *s, const char *msg)
void _tcp_cancel (const in_Header *ip, int icmp_type, int icmp_code, const char *msg, const void *arg)
Cancel a TCP socket.
static int tcp_read (_tcp_Socket *s, BYTE *buf, int maxlen)
Read from a TCP socket.
static int tcp_write (_tcp_Socket *s, const BYTE *data, UINT len)
Write data to a TCP connection.
static _tcp_Socket * tcp_findseq (const in_Header *ip, const tcp_Header *tcp)
Find the TCP socket that matches the tripplet: DESTADDR=MYADDR, DESTPORT=MYPORT and ACKNUM=SEQNUM+1 Can only be one socket.
static void tcp_sockreset (_tcp_Socket *s, BOOL proxy)
Resets a TCP connection.
static void tcp_no_arp (_tcp_Socket *s)
Called for a TCP socket when ARP lookup fails.
static BOOL tcp_checksum (const in_Header *ip, const tcp_Header *tcp, int len)
Verify the TCP header checksum.
static void tcp_rtt_win (_tcp_Socket *s)
Update retransmission timer, VJ algorithm and TCP windows.
static void tcp_upd_win (_tcp_Socket *s, unsigned line)
Check if receive window needs an update.
static __inline int tcp_opt_maxsegment (const _tcp_Socket *s, BYTE *opt)
TCP option routines.
static __inline int tcp_opt_timestamp (_tcp_Socket *s, BYTE *opt, DWORD ts_echo)
Insert TimeStamp option.
static __inline int tcp_opt_md5_sign (BYTE *opt)
static __inline void finalise_md5_sign (const in_Header *ip, const tcp_Header *tcp, WORD tcp_len, const char *secret)
static __inline int tcp_opt_padding (BYTE *opt, int len)
Pad options to multiple of 4 bytes.
static __inline int tcp_opt_winscale (const _tcp_Socket *s, BYTE *opt)
static __inline int tcp_opt_sack_ok (const _tcp_Socket *s, BYTE *opt)
static __inline int tcp_opt_sack (const _tcp_Socket *s, BYTE *opt, const struct SACK_list *sack)
static __inline int tcp_options (_tcp_Socket *s, BYTE *opt, BOOL is_syn)
Append options to output TCP header.
int _tcp_send (_tcp_Socket *s, const char *file, unsigned line)
Format and send an outgoing TCP segment.
int _tcp_send_reset (_tcp_Socket *s, const in_Header *his_ip, const tcp_Header *org_tcp, const char *file, unsigned line)
Format and send a reset (RST) tcp packet.
int _tcp_keepalive (_tcp_Socket *tcp)
TCP keepalive transmission.
int W32_CALL sock_keepalive (sock_type *s)
WORD W32_CALL sock_mode (sock_type *s, WORD mode)
VoidProc W32_CALL sock_yield (_tcp_Socket *s, VoidProc func)
Enable user defined yield function.
int W32_CALL sock_abort (sock_type *s)
Abort a UDP/TCP/Raw socket.
static int raw_read (_raw_Socket *raw, BYTE *buf, int maxlen)
Read data from a raw-socket.
int W32_CALL sock_read (sock_type *s, BYTE *buf, size_t maxlen)
Read a socket with maximum 'maxlen' bytes.
int W32_CALL sock_fastread (sock_type *s, BYTE *buf, int len)
Read a socket with maximum 'len' bytes.
int W32_CALL sock_write (sock_type *s, const BYTE *data, int len)
Writes data and returns length written.
int W32_CALL sock_fastwrite (sock_type *s, const BYTE *data, int len)
Simpler, non-blocking (non-looping) version of sock_write().
int W32_CALL sock_enqueue (sock_type *s, const BYTE *data, int len)
For UDP, this function is same as sock_write().
void W32_CALL sock_noflush (sock_type *s)
Sets non-flush mode on next TCP write.
void W32_CALL sock_flush (sock_type *s)
Send pending TCP data.
void W32_CALL sock_flushnext (sock_type *s)
Causes next transmission to have a flush (PUSH bit set).
int W32_CALL sock_close (sock_type *s)
Close a UDP/TCP socket.
void tcp_rtt_add (const _tcp_Socket *s, UINT rto, UINT MTU)
BOOL tcp_rtt_get (const _tcp_Socket *s, UINT *rto, UINT *MTU)
void tcp_rtt_clr (const _tcp_Socket *s)
Variables
char hostname [MAX_HOSTLEN+1] = "random-pc"
Our configured hostname.
unsigned _mss = ETH_MAX_DATA - TCP_OVERHEAD
unsigned _mtu = ETH_MAX_DATA
BOOL mtu_discover = 0
BOOL mtu_blackhole = 0
BOOL block_tcp = 0
when application handles TCP itself
BOOL block_udp = 0
when application handles UDP itself
BOOL block_icmp = 0
when application handles ICMP itself
BOOL block_ip = 0
when application handles IP itself
DWORD my_ip_addr = 0L
our IP address
DWORD sin_mask = 0xFFFFFF00L
our net-mask, 255.255.255.0
_udp_Socket * _udp_allsocs = NULL
list of udp-sockets
static BYTE * sign_opt
Prepare to insert MD5 option.
static struct tcp_rtt rtt_cache [RTTCACHE]
Round-trip timing cache routines.
Detailed Description
Main TCP handler.
PCTCP, the true worker of Waterloo TCP.
contains all opens, closes, major read/write routines and basic IP handler for incomming packets
Note: much of the TCP/UDP/IP layering is done at the data structure level, not in separate routines or tasks
Definition in file pctcp.c.
Function Documentation
_tcp_cancel()
void _tcp_cancel (const in_Header * ip, int icmp_type, int icmp_code, const char * msg, const void * arg)
Cancel a TCP socket.
Called upon receiving ICMP errors: host/port UNREACH, REDIRECT, SOURCEQUENCH, TIMXCEED or PARAMPROB. See icmp_redirect() or icmp_handler().
Note: 'ip' is a small copy of the IP-packet originating the ICMP message. We may not have received a copy of the original TCP-header. But we probably won't do any harm if got less TCP-header data than needed. I.e. src_port/dst_port will be zero.
Definition at line 1748 of file pctcp.c.
_tcp_close()
void _tcp_close (_tcp_Socket * s)
Close a TCP connection.
Send a FIN on a particular port – only works if it is open. Must still allow receives.
Definition at line 459 of file pctcp.c.
References tcp_Socket::flags, tcp_Socket::rtt_time, set_timeout(), tcp_Socket::state, tcp_Socket::timeout, tcp_Socket::tx_datalen, and tcp_Socket::unhappy.
_tcp_handler()
_tcp_Socket* _tcp_handler (const in_Header * ip, BOOL broadcast)
The main TCP input handler.
All TCP input processing is done from here.
Definition at line 649 of file pctcp.c.
_tcp_keepalive()
int _tcp_keepalive (_tcp_Socket * tcp)
TCP keepalive transmission.
If connection is idle (tx_datalen == 0), force the peer to send us a segment by sending a keep-alive packet:
*    <SEQ=SND.UNA-1><ACK=RCV.NXT><CTL=ACK>
*
Definition at line 2715 of file pctcp.c.
_tcp_send()
int _tcp_send (_tcp_Socket * s, const char * file, unsigned line)
Format and send an outgoing TCP segment.
Several packets may be sent depending on peer's window.
Definition at line 2352 of file pctcp.c.
_tcp_send_reset()
int _tcp_send_reset (_tcp_Socket * s, const in_Header * his_ip, const tcp_Header * org_tcp, const char * file, unsigned line)
Format and send a reset (RST) tcp packet.
Note
We modify the orignal segment (orig_tcp) to use it for sending.
Definition at line 2568 of file pctcp.c.
_tcp_sendsoon()
int _tcp_sendsoon (_tcp_Socket * s, const char * file, unsigned line)
Schedule a transmission pretty soon.
This one has an imperfection at midnight, but it is not significant to the connection performance.
Note
gv: Added - 5 May 2000: Relax retransmission period to tcp_CLOSE_TO when CLOSEWT state is entered.
Relax retransmission period to tcp_OPEN_TO in SYNSENT state.
Definition at line 559 of file pctcp.c.
_tcp_unthread()
_tcp_Socket* _tcp_unthread (_tcp_Socket * ds, BOOL free_tx)
Unthread a socket from the tcp socket list, if it's there.
Free Tx-buffer if set in tcp_set_window().
Definition at line 600 of file pctcp.c.
_udp_cancel()
void _udp_cancel (const in_Header * ip, int icmp_type, int icmp_code, const char * msg, const void * arg)
Cancel an UDP socket.
Called upon receiving ICMP errors: REDIRECT, TIMXCEED, PARAMPROB, or host/port UNREACH. See icmp_redirect() or icmp_handler().
Definition at line 1640 of file pctcp.c.
raw_read()
static int raw_read (_raw_Socket * raw, BYTE * buf, int maxlen) static
Read data from a raw-socket.
Don't copy IP-header to buf.
Definition at line 2866 of file pctcp.c.
References _raw_Socket::used.
sock_enqueue()
int W32_CALL sock_enqueue (sock_type * s, const BYTE * data, int len)
For UDP, this function is same as sock_write().
For TCP, this function enqueues 'data' to transmit queue.
Note
user must not touch 'data' while sock_tbused() returns > 0.
Definition at line 3061 of file pctcp.c.
sock_fastread()
int W32_CALL sock_fastread (sock_type * s, BYTE * buf, int len)
Read a socket with maximum 'len' bytes.
Note
does not busywait until buffer is full.
Definition at line 2948 of file pctcp.c.
References _raw_Socket::ip_type, raw_read(), tcp_read(), and udp_read().
sock_fastwrite()
int W32_CALL sock_fastwrite (sock_type * s, const BYTE * data, int len)
Simpler, non-blocking (non-looping) version of sock_write().
Note
UDP writes may truncate; check the return value.
Definition at line 3035 of file pctcp.c.
sock_flush()
void W32_CALL sock_flush (sock_type * s)
Send pending TCP data.
If there is Tx-data to be sent, set the PUSH bit.
Definition at line 3120 of file pctcp.c.
References tcp_Socket::flags, tcp_Socket::send_una, and tcp_Socket::tx_datalen.
sock_read()
int W32_CALL sock_read (sock_type * s, BYTE * buf, size_t maxlen)
Read a socket with maximum 'maxlen' bytes.
Note
busywaits until 'buf' is full (and call 's->usr_yield').
Return values
0 socket is not open.
<=maxlen socket has data to be read.
Definition at line 2892 of file pctcp.c.
References raw_read(), tcp_read(), tcp_tick(), and udp_read().
sock_reduce_mss()
static void sock_reduce_mss (sock_type * s, WORD MTU) static
Reduce socket MSS upon receiving ICMP_UNREACH_NEEDFRAG.
'MTU' is next-hop suggested MTU or 0 if router doesn't support RFC-1191.
Definition at line 1611 of file pctcp.c.
References tcp_Socket::max_seg.
sock_write()
int W32_CALL sock_write (sock_type * s, const BYTE * data, int len)
Writes data and returns length written.
Note
sends with PUSH-bit (flush data).
repeatedly calls 's->usr_yield'.
UDP packetsare sent in chunks of MTU-28.
Return values
0 if some error in lower layer.
'len' if all data sent okay.
Definition at line 2977 of file pctcp.c.
sock_yield()
VoidProc W32_CALL sock_yield (_tcp_Socket * s, VoidProc func)
Enable user defined yield function.
Return address of previous yield function.
Definition at line 2820 of file pctcp.c.
tcp_checksum()
static BOOL tcp_checksum (const in_Header * ip, const tcp_Header * tcp, int len) static
Verify the TCP header checksum.
Note
Not used for IPv6.
Definition at line 2050 of file pctcp.c.
tcp_listen()
int W32_CALL tcp_listen (_tcp_Socket * s, WORD lport, DWORD ip, WORD port, ProtoHandler handler, WORD timeout)
Passively opens TCP a connection.
Listen for a connection on a particular port
<
Todo:
use mss from setsockopt()
Definition at line 393 of file pctcp.c.
tcp_no_arp()
static void tcp_no_arp (_tcp_Socket * s) static
Called for a TCP socket when ARP lookup fails.
If socket allocated by BSD API, do a read wakeup on it.
Definition at line 2025 of file pctcp.c.
tcp_open()
int W32_CALL tcp_open (_tcp_Socket * s, WORD lport, DWORD ip, WORD rport, ProtoHandler handler)
Actively open a TCP connection.
Make connection to a particular destination. Not used for IPv6 (see _TCP6_open()).
Return values
0 on error. 's->err_msg' filled.
Note
'lport' is local port to associate with the connection.
'rport' is remote port for same connection.
<
Todo:
use mss from setsockopt()
Todo:
use TCP_NODELAY set in setsockopt()
Definition at line 312 of file pctcp.c.
tcp_opt_maxsegment()
static __inline int tcp_opt_maxsegment (const _tcp_Socket * s, BYTE * opt) static
TCP option routines.
Note
Each of these MUST add multiple of 4 bytes of options. Insert MSS option.
Definition at line 2192 of file pctcp.c.
tcp_opt_timestamp()
static __inline int tcp_opt_timestamp (_tcp_Socket * s, BYTE * opt, DWORD ts_echo) static
Insert TimeStamp option.
nmap uses TSval (ts_now) as indication of uptime, so send
of msec since started.
Definition at line 2205 of file pctcp.c.
tcp_read()
static int tcp_read (_tcp_Socket * s, BYTE * buf, int maxlen) static
Read from a TCP socket.
buf where to put data.
Note
does large buffering.
Definition at line 1841 of file pctcp.c.
tcp_Retransmitter()
void tcp_Retransmitter (BOOL force)
Called periodically to perform retransmissions.
if 'force == 1' do it now.
< dup ACK counter ?
<
Todo:
set "Slow-start" threshold
<
Todo:
Allow for 3 SYN before giving up
Definition at line 1222 of file pctcp.c.
tcp_rtt_win()
static void tcp_rtt_win (_tcp_Socket * s) static
Update retransmission timer, VJ algorithm and TCP windows.
Only called after we received something on socket.
Todo:
Use the threshold to signify "end-of-Slow-Start" (equilibrium)
Definition at line 2076 of file pctcp.c.
tcp_tick()
WORD W32_CALL tcp_tick (sock_type * s)
Must be called periodically by user application (or BSD socket API).
if 's != NULL', check this socket for timeout.
if 's == NULL', check all sockets in list.
Return values
0 if 's' is non-NULL and 's' closes.
!0 if 's' is NULL or 's' is still open.
Don't enter this loop if reentered. That could return the same packet twice (before we call _eth_free() on the 1st packet).
Todo:
Limit the time spent here (clamp # of loops)
Definition at line 1402 of file pctcp.c.
References _tcp_unthread(), and tcp_Socket::state.
tcp_write()
static int tcp_write (_tcp_Socket * s, const BYTE * data, UINT len) static
Write data to a TCP connection.
Return values
>0 Number of bytes written.
0 Connection is not established.
-1 Error in lower layer.
Definition at line 1889 of file pctcp.c.
udp_demux()
static _udp_Socket* udp_demux (const in_Header * ip, BOOL ip_bcast, DWORD destin, WORD srcPort, WORD dstPort, BOOL * udp_err) static
Demultiplexer for incoming UDP packets.
Don't debug packet if no match was found (except if '*udp_err').
Demux to active sockets.
Todo:
use some kind of hashing to speed up the search.
Definition at line 877 of file pctcp.c.
udp_open()
int W32_CALL udp_open (_udp_Socket * s, WORD lport, DWORD ip, WORD port, ProtoHandler handler)
UDP active open.
Open a connection on a particular port.
Definition at line 196 of file pctcp.c.
udp_read()
static int udp_read (_udp_Socket * s, BYTE * buf, int maxlen) static
Read from UDP socket.
buf where data is put.
maxlen read max this amount.
Note
does large buffering.
Definition at line 1584 of file pctcp.c.
udp_write()
static int udp_write (_udp_Socket * s, const BYTE * data, int len) static
Write an UDP packet.
Note
Assumes data fits in one datagram, else only the first fragment will be sent! Because MTU is used for splits, the guaranteed max data size is 'MTU - UDP_OVERHEAD = 548' for a non-fragmented datagram. Routers should handle at least 576 bytes datagrams.
Definition at line 1504 of file pctcp.c.
Variable Documentation
hostname
char hostname[MAX_HOSTLEN+1] = "random-pc"
Our configured hostname.
Not the FQDN.
Definition at line 59 of file pctcp.c.
mtu_blackhole
BOOL mtu_blackhole = 0
Todo:
Add PMTU blackhole detection
Definition at line 64 of file pctcp.c.
mtu_discover
BOOL mtu_discover = 0
Todo:
Add PMTU discovery method
Definition at line 63 of file pctcp.c.
rtt_cache
struct tcp_rtt rtt_cache[RTTCACHE] static
Round-trip timing cache routines.
These functions implement a very simple system for keeping track of network performance for future use in new connections. The emphasis here is on speed of update (rather than optimum cache hit ratio) since tcp_rtt_add() is called every time a TCP connection updates its round trip estimate.
Note
'rto' is either in ticks or milli-sec depending on if PC has an 8254 Time chip.
These routines are modified versions from KA9Q by Phil Karn.
Definition at line 3190 of file pctcp.c.