Watt-32 tcp/ip: /home/fosco/src/SSH2DOS/watt32/src/presaddr.c File Reference
presaddr.c File Reference
Functions
static const char * inet_ntop4 (const u_char *src, char *dst, size_t size)
Format an IPv4 address, more or less like inet_ntoa().
static int inet_pton4 (const char *src, u_char *dst)
Like inet_aton() but without all the hexadecimal and shorthand.
static const char * inet_ntop6 (const u_char *src, char *dst, size_t size)
Convert IPv6 binary address into presentation (printable) format.
static int inet_pton6 (const char *src, u_char *dst)
Convert presentation level address to network order binary form.
const char *W32_CALL inet_ntop (int af, const void *src, char *dst, size_t size)
Convert a network format address to presentation format.
const char *W32_CALL _w32_inet_ntop (int af, const void *src, char *dst, size_t size)
int W32_CALL inet_pton (int af, const char *src, void *dst)
Convert from presentation format (which usually means ASCII printable) to network format (which is usually some kind of binary format).
int W32_CALL _w32_inet_pton (int af, const char *src, void *dst)
int main (int argc, char **argv)
Detailed Description
Convert network addresses to printable format.
Definition in file presaddr.c.
Function Documentation
inet_ntop()
const char* W32_CALL inet_ntop (int af, const void * src, char * dst, size_t size)
Convert a network format address to presentation format.
Return values
pointer to presentation format address (`dst'),
NULL on error (see errno).
Author
Paul Vixie, 1996.
Definition at line 40 of file presaddr.c.
References inet_ntop4(), and inet_ntop6().
inet_ntop4()
static const char * inet_ntop4 (const u_char * src, char * dst, size_t size) static
Format an IPv4 address, more or less like inet_ntoa().
Return values
`dst' (as a const)
Note
uses no statics
takes a u_char* not an in_addr as input
Author
Paul Vixie, 1996.
Definition at line 100 of file presaddr.c.
inet_ntop6()
static const char * inet_ntop6 (const u_char * src, char * dst, size_t size) static
Convert IPv6 binary address into presentation (printable) format.
Author
Paul Vixie, 1996.
Definition at line 118 of file presaddr.c.
inet_pton()
int W32_CALL inet_pton (int af, const char * src, void * dst)
Convert from presentation format (which usually means ASCII printable) to network format (which is usually some kind of binary format).
Return values
1 the address was valid for the specified address family.
0 the address wasn't valid (`dst' is untouched in this case).
-1 some other error occurred (`dst' is untouched in this case, too).
Author
Paul Vixie, 1996.
Definition at line 70 of file presaddr.c.
References inet_pton4(), and inet_pton6().
inet_pton4()
static int inet_pton4 (const char * src, u_char * dst) static
Like inet_aton() but without all the hexadecimal and shorthand.
Return values
1 if `src' is a valid dotted quad
0 if `src' is not a valid dotted quad.
Note
does not touch `dst' unless it's returning 1.
Author
Paul Vixie, 1996.
Definition at line 231 of file presaddr.c.
inet_pton6()
static int inet_pton6 (const char * src, u_char * dst) static
Convert presentation level address to network order binary form.
Return values
1 if `src' is a valid [RFC1884 2.2] address.
0 otherwise.
Note
does not touch `dst' unless it's returning 1.
`::' in a full address is silently ignored.
Author
Paul Vixie, 1996.
credit: inspired by Mark Andrews.
Definition at line 289 of file presaddr.c.